version: '3.5'

services:
  etcd:
    container_name: milvus-etcd
    image: quay.io/coreos/etcd:latest
    command: etcd -listen-peer-urls=http://127.0.0.1:2380 -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379,http://0.0.0.0:4001 -initial-advertise-peer-urls=http://127.0.0.1:2380 --initial-cluster default=http://127.0.0.1:2380
    networks:
      - milvus

  pulsar:
    container_name: milvus-pulsar
    image: apachepulsar/pulsar:latest
    command: bin/pulsar standalone
    networks:
      - milvus

  minio:
    container_name: milvus-minio
    image: minio/minio:RELEASE.2020-12-03T00-03-10Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    command: minio server /minio_data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - milvus

  rootcoord:
    container_name: milvus-rootcoord
    image: milvusdb/milvus:latest
    command: ["milvus", "run", "rootcoord"]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      PULSAR_ADDRESS: pulsar://pulsar:6650
      DATA_SERVICE_ADDRESS: datacoord:13333
      INDEX_SERVICE_ADDRESS: indexcoord:31000
      QUERY_SERVICE_ADDRESS: querycoord:19531
    depends_on:
      - "etcd"
      - "pulsar"
      - "minio"
    networks:
      - milvus

  proxy:
    container_name: milvus-proxy
    image: milvusdb/milvus:latest
    command: ["milvus", "run", "proxy"]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      PULSAR_ADDRESS: pulsar://pulsar:6650
      MASTER_ADDRESS: master:53100
      DATA_SERVICE_ADDRESS: datacoord:13333
      INDEX_SERVICE_ADDRESS: indexcoord:31000
      QUERY_SERVICE_ADDRESS: querycoord:19531
    ports:
      - "19530:19530"
    networks:
      - milvus

  querycoord:
    container_name: milvus-querycoord
    image: milvusdb/milvus:latest
    command: ["milvus", "run", "querycoord"]
    environment:
      MASTER_ADDRESS: master:53100
      DATA_SERVICE_ADDRESS: datacoord:13333
    depends_on:
      - "etcd"
      - "pulsar"
      - "minio"
    networks:
      - milvus

  querynode:
    container_name: milvus-querynode
    image: milvusdb/milvus:latest
    command: ["milvus", "run", "querynode"]
    environment:
      MINIO_ADDRESS: minio:9000
      PULSAR_ADDRESS: pulsar://pulsar:6650
      MASTER_ADDRESS: master:53100
      DATA_SERVICE_ADDRESS: datacoord:13333
      INDEX_SERVICE_ADDRESS: indexcoord:31000
      QUERY_SERVICE_ADDRESS: querycoord:19531
    depends_on:
      - "querycoord"
    networks:
      - milvus

  indexcoord:
    container_name: milvus-indexcoord
    image: milvusdb/milvus:latest
    command: ["milvus", "run", "indexcoord"]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
      MASTER_ADDRESS: master:53100
    depends_on:
      - "etcd"
      - "pulsar"
      - "minio"
    networks:
      - milvus

  indexnode:
    container_name: milvus-indexnode
    image: milvusdb/milvus:latest
    command: ["milvus", "run", "indexnode"]
    environment:
      MINIO_ADDRESS: minio:9000
      INDEX_SERVICE_ADDRESS: indexcoord:31000
    depends_on:
      - "indexcoord"
    networks:
      - milvus

  datacoord:
    container_name: milvus-datacoord
    image: milvusdb/milvus:latest
    command: ["milvus", "run", "datacoord"]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
      PULSAR_ADDRESS: pulsar://pulsar:6650
      MASTER_ADDRESS: master:53100
    depends_on:
      - "etcd"
      - "pulsar"
      - "minio"
    networks:
      - milvus

  datanode:
    container_name: milvus-datanode
    image: milvusdb/milvus:latest
    command: ["milvus", "run", "datanode"]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
      PULSAR_ADDRESS: pulsar://pulsar:6650
      MASTER_ADDRESS: master:53100
      DATA_SERVICE_ADDRESS: datacoord:13333
    depends_on:
      - "datacoord"
    networks:
      - milvus

networks:
  milvus:
