run:
  skip-dirs:
    - build
    - configs
    - deployments
    - docs
    - scripts
    - internal/core

linters-settings:
  golint:
    min-confidence: 0

  misspell:
    locale: US

linters:
  disable-all: false
  enable:
    - typecheck
    - goimports
    - misspell
    - govet
    - golint
    - ineffassign
    - gosimple
    - deadcode
    - structcheck

service:
  golangci-lint-version: 1.27.0 # use the fixed version to not introduce new linters unexpectedly

