#Configuration File for CodeCov
coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        threshold: 0% #Allow the coverage to drop by threshold%, and posting a success status.
        branches:
          - master
    patch:
      default:
        target: 70%
        threshold: 0%
        branches:
          - master

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  branches: # branch names that can post comment
    - master

ignore:
  - "LICENSES"
  - ".git"
  - "*.yml"
  - "*.md"
  - "docs/.*"
