version: '3.5'

x-ccache: &ccache
  CCACHE_COMPILERCHECK: content
  CCACHE_COMPRESS: 1
  CCACHE_COMPRESSLEVEL: 5
  CCACHE_MAXSIZE: 2G
  CCACHE_DIR: /ccache

services:
  ubuntu:
    image: ${REPO}:${ARCH}-ubuntu${UBUNTU}-${SHOW_DATE}
    build:
      context: .
      dockerfile: build/docker/env/cpu/ubuntu${UBUNTU}/Dockerfile
      cache_from:
        - ${REPO}:${ARCH}-ubuntu${UBUNTU}-${SHOW_DATE}
    shm_size: 2G
    environment:
      <<: *ccache
    volumes: &ubuntu-volumes
      - .:/milvus-distributed:delegated
      - ${DOCKER_VOLUME_DIRECTORY:-.docker}/${ARCH}-ubuntu${UBUNTU}-cache:/ccache:delegated
    working_dir: "/milvus-distributed"
    command: &ubuntu-command >
      /bin/bash -c "
        make verifiers && make all"
