apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: test-query-node-pod-kill
  namespace:
spec:
  action: pod-kill
  mode: one
  selector:
    namespaces:
      - default         # target namespace of milvus deployment
    labelSelectors:
      app.kubernetes.io/name: milvus-ha
      component: 'querynode'
  scheduler:
    cron: '@every 20s'
