# Copyright (C) 2019-2020 Zilliz. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance
# with the License. You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under the License
# is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
# or implied. See the License for the specific language governing permissions and limitations under the License.

msgChannel:
  # channel name generation rule: ${namePrefix}-${ChannelIdx}
  chanNamePrefix:
    dataDefinition: "data-definition"
    masterTimeTick: "master-timetick"
    masterStatistics: "master-statistics"
    insert: "insert"
    delete: "delete"
    search: "search"
    searchResult: "searchResult"
    k2s: "k2s"
    proxyTimeTick: "proxyTimeTick"
    proxyServiceTimeTick: "proxyServiceTimeTick"
    dataNodeTimeTick: "dataNodeTimeTick"
    queryTimeTick: "queryTimeTick"
    dataNodeSegStatistics: "dataNodeSegStatistics"
    queryNodeStats: "query-node-stats"
    # cmd for loadIndex, flush, etc...
    cmd: "cmd"
    dataServiceInsertChannel: "insert-channel-"
    dataServiceStatistic: "dataservice-statistics-channel"
    dataServiceTimeTick: "dataservice-timetick-channel"
    dataServiceSegmentInfo: "segment-info-channel"

  # sub name generation rule: ${subNamePrefix}-${NodeID}
  subNamePrefix:
    masterSubNamePrefix: "master"
    proxySubNamePrefix: "proxy"
    queryNodeSubNamePrefix: "queryNode"
    dataNodeSubNamePrefix: "dataNode"
    dataServiceSubNamePrefix: "dataService"

  # default channel range [0, 1)
  channelRange:
    insert: [0, 2]
    delete: [0, 1]
    dataDefinition: [0,1]
    k2s: [0, 1]
    search: [0, 1]
    searchResult: [0, 1]
