version: '2.3'

networks:
    monitor:
        driver: bridge

services:
    milvus_server:
        runtime: nvidia
        image: milvusdb/milvus:latest
        restart: always
        environment:
            WEB_APP: host.docker.internal
        volumes:
            - ../core/conf/milvus.yaml:/var/lib/milvus/conf/milvus.yaml
            - ../core/conf/log_config.conf:/var/lib/milvus/conf/log_config.conf
        ports:
            - "8080:8080"
            - "19530:19530"
        networks:
            - monitor
