# Copyright (C) 2019-2020 Zilliz. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance
# with the License. You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under the License
# is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
# or implied. See the License for the specific language governing permissions and limitations under the License.


nodeID: # will be deprecated after v0.2
  proxyIDList: [0]
  queryNodeIDList: [1, 2]
  writeNodeIDList: [3] # GOOSE TODO: remove this
  dataNodeIDList: [3] 

etcd:
  address: localhost
  port: 2379
  rootPath: by-dev
  metaSubPath: meta # metaRootPath = rootPath + '/' + metaSubPath
  kvSubPath: kv # kvRootPath = rootPath + '/' + kvSubPath
  segFlushMetaSubPath: datanode/segment # Full Path = rootPath/metaSubPath/segFlushMetaSubPath
  ddlFlushMetaSubPath: datanode/ddl     # Full Path = rootPath/metaSubPaht/ddlFlushMetaSubPath
  writeNodeSegKvSubPath: writer/segment # GOOSE TODO: remove this
  writeNodeDDLKvSubPath: writer/ddl # GOOSE TODO: remove this
  segThreshold: 10000

minio:
  address: localhost
  port: 9000
  accessKeyID: minioadmin
  secretAccessKey: minioadmin
  useSSL: false
  bucketName: "a-bucket"

pulsar:
  address: localhost
  port: 6650
  authentication: false
  user: user-default
  token: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJKb2UifQ.ipevRNuRP6HflG8cFKnmUPtypruRC4fb1DWtoLL62SY

master:
  address: localhost
  port: 53100

proxyNode:
  address: localhost
  port: 19530

queryService:
  address: localhost
  port: 19531

proxyService:
  address: localhost
  port: 19530

queryNode:
  gracefulTime: 5000 #ms

indexBuilder:
    address: localhost
    port: 31000

indexServer:
  address: localhost
  port: 31000

dataNode:
  address: localhost
  port: 21124
