name: add contributor

on:
    schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '50 11 * * *'

jobs:
  contributor:
    runs-on: ubuntu-latest
    steps:
      - uses: milvus-io/hero-bot@1.3
        with:
          token: ${{ secrets.ALL_CONTRIBUTORS_TOKEN }}
          repos: 'milvus-io/milvus,milvus-io/pymilvus'
          targetRepo: 'milvus-io/milvus'

