name: all-contributors

on:
    schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '10 9 * * *'

jobs:
  contributor:
    runs-on: ubuntu-latest
    steps:
      # Update README.md
      - uses: milvus-io/hero-bot@1.4
        with:
          token: ${{ secrets.ALL_CONTRIBUTORS_TOKEN }}
          repos: 'milvus-io/milvus,bootcamp,community,docs,milvus-helm,milvus-sdk-go,milvus-sdk-java,milvus-sdk-node,milvus.io,pymilvus,pymilvus-orm'
          targetRepo: 'milvus-io/milvus'
          filePath: 'README.md'

      # Update README_CN.md
      - uses: milvus-io/hero-bot@1.4
        with:
          token: ${{ secrets.ALL_CONTRIBUTORS_TOKEN }}
          repos: 'milvus-io/milvus,bootcamp,community,docs,milvus-helm,milvus-sdk-go,milvus-sdk-java,milvus-sdk-node,milvus.io,pymilvus,pymilvus-orm'
          targetRepo: 'milvus-io/milvus'
          filePath: 'README_CN.md'

