name: Build and test
# TODO: do not trigger action for some document file update

# This workflow is triggered on pushes or pull request to the repository.
on:
  push:
    # file paths to consider in the event. Optional; defaults to all.
    paths:
      - 'ci/**'
      - 'internal/**'
      - 'cmd/**'
      - '.github/workflows/main.yml'
      - docker-compose.yml
      - '!**.md'
      - '!**_test.go'
      - '!ci/jenkins/**'
  pull_request:
    # file paths to consider in the event. Optional; defaults to all.
    paths:
      - 'ci/**'
      - 'internal/**'
      - 'cmd/**'
      - '.github/workflows/main.yml'
      - docker-compose.yml
      - '!**.md'
      - '!**_test.go'
      - '!ci/jenkins/**'

jobs:
  ubuntu:
    name: AMD64 ubuntu-18.04
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Dependency
        run: |
          ./ci/scripts/install_deps.sh
          go get github.com/golang/protobuf/protoc-gen-go@v1.3.2
      - name: Cache Core Thirdparty
        id: cache-core
        uses: actions/cache@v2
        with:
          path: |
            ./internal/core/cmake_build
          key: ${{ runner.os }}-core-thirdparty
      - name: Build Cpp
        run: |
          ./ci/scripts/core_build.sh -u
      - name: Generat Proto GO File
        run: |
          echo `pwd`
          export PATH=$PATH:$(go env GOPATH)/bin
          export protoc=./internal/core/cmake-build-release/thirdparty/protobuf/protobuf-build/protoc
          ./ci/scripts/proto_gen_go.sh
      - name: Build GO
        run: |
          go build -o ./cmd/writer/writer ./cmd/writer/writer.go
          go build -o ./cmd/reader/reader ./cmd/reader/reader.go
          go build -o ./cmd/master/master ./cmd/master/master.go
          go build -o ./cmd/proxy/proxy ./cmd/proxy/proxy.go
      - name: Docker Pull And Run
        run: |
          docker-compose up -d
      - name: Run Unittest
        run: |
          ./ci/scripts/run_unittest.sh
