name: Publish Gpu Builder
# TODO: do not trigger action for some document file update

# This workflow is triggered on pushes or pull request to the repository.
on:
  push:
    # file paths to consider in the event. Optional; defaults to all.
    paths:
      - 'build/docker/builder/gpu/**'
      - '.github/workflows/publish-gpu-builder.yaml'
      - '!**.md'
  pull_request:
    # file paths to consider in the event. Optional; defaults to all.
    paths:
      - 'build/docker/builder/gpu/**'
      - '.github/workflows/publish-gpu-builder.yaml'
      - '!**.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  publish-gpu-builder:
    name: ${{ matrix.arch }} ${{ matrix.os }}
    runs-on: ubuntu-latest
    timeout-minutes: 500
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu20.04]
        arch: [amd64]
    env:
      OS_NAME: ${{ matrix.os }}
      IMAGE_ARCH: ${{ matrix.arch }}
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        if: ${{ ! startsWith(runner.name, 'self') }} # skip this step if it is self-hosted runner
        with:
          root-reserve-mb: 20480
          # overprovision-lvm: 'true'
          swap-size-mb: 1024
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get version from system time after release step
        id: extracter
        run: |
          echo "::set-output name=version::$(date +%Y%m%d)"
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      # - name: Setup upterm session
      #   uses: lhotari/action-upterm@v1
      - name: Docker Build
        if: success() && github.event_name == 'pull_request' && github.repository == 'milvus-io/milvus'
        shell: bash
        run: |
          docker info
          docker build -t milvusdb/milvus-env:gpu-${OS_NAME}-${{ steps.extracter.outputs.version }}-${{ steps.extracter.outputs.sha_short }} -f build/docker/builder/gpu/${OS_NAME}/Dockerfile .
      - name: Docker Build&Push
        if: success() && github.event_name == 'push' && github.repository == 'milvus-io/milvus'
        shell: bash
        run: |
          docker info
          docker login -u ${{ secrets.DOCKERHUB_USER }} \
                       -p ${{ secrets.DOCKERHUB_TOKEN }}
          # Building the first image
          docker build -t milvusdb/milvus-env:gpu-${OS_NAME}-${{ steps.extracter.outputs.version }}-${{ steps.extracter.outputs.sha_short }} -f build/docker/builder/gpu/${OS_NAME}/Dockerfile .
          docker push milvusdb/milvus-env:gpu-${OS_NAME}-${{ steps.extracter.outputs.version }}-${{ steps.extracter.outputs.sha_short }}

          # Building the second image
          docker build -t milvusdb/milvus-env:gpu-${OS_NAME}-latest -f build/docker/builder/gpu/${OS_NAME}/Dockerfile .
          docker push milvusdb/milvus-env:gpu-${OS_NAME}-latest
      - name: Bump Builder Version
        if: success() && github.event_name == 'push' && github.repository == 'milvus-io/milvus' && matrix.os == 'ubuntu20.04'
        uses: ./.github/actions/bump-builder-version
        with:
          tag: "${{ steps.extracter.outputs.version }}-${{ steps.extracter.outputs.sha_short }}"
          type: gpu
          token: ${{ secrets.ALL_CONTRIBUTORS_TOKEN }}